### ISSUE TITLE
nested repeat loops use the same iterator variable

### ISSUE THREAD

**Issue by jsseng** [jsseng/arduino_robot#48]

**Comment by ooee123** [comment]
Something like this right?

```
variable i = 5 
variable j = 8 
variable k = 2 

repeat i times {
   repeat j times {
      k = k + 1 
   }   
}

display k
```
That will get translated into...
```
{
   int rptCnt;
   for (rptCnt = 0; rptCnt < i; rptCnt++)
   {   
      {   
         int rptCnt;
         for (rptCnt = 0; rptCnt < j; rptCnt++)
         {
            k = (k + 1); 
         }
      }   
   }   
}
```
By static scoping, the 2 variables occupy a different piece of memory because of all those extra braces. So although true, they use the same iterator identifier, they are not the same variable.

Just tested the following as C code and as Arduino compiled code. Both produce the answer of 42
