### ISSUE TITLE
"test" does not throw error

### ISSUE THREAD

**Issue by jsseng** [jsseng/arduino_robot#64]
When I compile a file that contains only:

```
"test"
```
there is no error generated.

**Comment by ooee123** [comment]
I just tried that and got an error that it
"Expected a statement, found a lonely identifier with the next token of eof"

The Translator sees the non-Bumblebee-keyword of test and thinks it's a identifier name, but then the file ends and see eof. An identifier by itself is not a statement (because it does nothing), so right now, we have it complain.

**Comment by ooee123** [comment]
I have however noticed this error message does not have the Line number syntax at the end. I have just pushed a version that fixes that
